### ISSUE TITLE
Small Browser Size Styling Problems

### ISSUE THREAD

**Issue by itsdavidmorgan** [Leeflets/leeflets#60] opened 2013-03-26 04:15 UTC
There seems to be a number of little styling defects that occurs if Leeflets is loaded in a browser width less than 760 pixels. Icons and padding are messed up... seems to be caused by some bootstrap styles.

![Screen Shot 2013-03-25 at 6 08 35 PM](https://f.cloud.github.com/assets/1852322/301332/0b0f2ad0-95cb-11e2-8f1c-9d1ec31f4077.png)

**Comment by bradt** [comment] 2013-03-26 13:15
Duplicate of #56 which was fixed yesterday. Please pull the latest from Github and test again.

**Closed as completed by bradt** 2013-03-26 13:15 UTC
